# Use an official Python runtime as the parent image
FROM nginx:latest

# Copy the HTML files and entrypoint script into the container
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./entrypoint.sh /app/entrypoint.sh

ENV WS_BACK_URL=http://localhost:8080

# Make sure the script is executable
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
