# Use an official Python runtime as the parent image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable to specify the Flask app entry point
ENV FLASK_APP=app.py

# Run the Flask application
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
